matrix:
  include:
    - language: node_js
      node_js:
        - "12.13.1"
      before_script:
        - cd server
      script:
        - npm install
        - npm test
    
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - android-25
          - build-tools-25.0.3
      script:
        - cd android_app
        - ./gradlew test